# Generated by Django 6.1.1 on 2026-09-23 22:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Servicio')),
            ],
            options={
                'verbose_name': 'Servicios',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CO')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('ADMIN_H', 'Administrador_hotel'), ('ADMIN_R', 'Administrador_Restaurante'), ('GUIA', 'Guia'), ('TURISTA', 'Turista')], default='TURISTA', max_length=10, verbose_name='Rol')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('PPT', 'Permiso de Permanecia Temporal'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('NU', 'Otro')], default='CC', max_length=5, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de documento')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_admin', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de usuario')),
            ],
            options={
                'verbose_name': 'Administrador general',
                'verbose_name_plural': 'Administradores generales',
            },
        ),
        migrations.CreateModel(
            name='restaurantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Detalles')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('pais', models.CharField(default='Colombia', max_length=100, verbose_name='Pais')),
                ('url_img', models.ImageField(blank=True, null=True, upload_to='restaurantes/', verbose_name='Imagen del Restaurante')),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_admin_restaurante', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de usuario')),
                ('servicios', models.ManyToManyField(blank=True, related_name='Restaurantes', to='usuarios.servicios', verbose_name='Servicios Ofrecidos')),
            ],
            options={
                'verbose_name': 'Administrador de Restaurante',
                'verbose_name_plural': 'Administradores de Restaurantes',
            },
        ),
        migrations.CreateModel(
            name='hoteles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Detalles')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('pais', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('url_img', models.ImageField(blank=True, null=True, upload_to='hoteles/', verbose_name='Imagen del Hotel')),
                ('rtn', models.CharField(max_length=50, unique=True, verbose_name='Registro Nacional de Turismo (RNT/RTN)')),
                ('registro_sanitario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Registro Sanitario')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_admin_hotel', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de Usuario')),
                ('servicios', models.ManyToManyField(blank=True, related_name='Hoteles', to='usuarios.servicios', verbose_name='Servicios Ofrecidos')),
            ],
            options={
                'verbose_name': 'Administrador de Hotel',
                'verbose_name_plural': 'Administradores de Hoteles',
            },
        ),
    ]
