# Generated by Django 6.1.1 on 2026-10-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='licencia_sanitaria',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to='', verbose_name='Registro Sanitario'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='licencia_sanitaria',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to='', verbose_name='Registro Sanitario'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='pais',
            field=models.CharField(blank=True, default='Colombia', max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rtn',
            field=models.FileField(max_length=50, unique=True, upload_to='', verbose_name='Registro Nacional de Turismo (RNT/RTN)'),
        ),
    ]
