# Generated by Django 6.1.1 on 2026-09-28 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('PPT', 'Permiso de Permanecia Temporal'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('NU', 'Otro')], default='CC', max_length=5, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Numero de documento')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimineto')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('PPT', 'Permiso de Permanecia Temporal'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('NU', 'Otro')], default='CC', max_length=5, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Numero de documento')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimineto')),
                ('certificado_turismo', models.ImageField(blank=True, null=True, upload_to='certificados_guias/', verbose_name='Certificado de Turismo')),
            ],
            options={
                'verbose_name': 'Guia',
                'verbose_name_plural': 'Guias',
            },
            bases=('usuarios.usuario',),
        ),
    ]
