# Generated by Django 6.1.1 on 2026-09-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_cliente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('PPT', 'Permiso de Permanecia Temporal'), ('RC', 'Registro Civil'), ('NU', 'Otro')], default='CC', max_length=5, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('PPT', 'Permiso de Permanecia Temporal'), ('RC', 'Registro Civil'), ('NU', 'Otro')], default='CC', max_length=5, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('PPT', 'Permiso de Permanecia Temporal'), ('RC', 'Registro Civil'), ('NU', 'Otro')], default='CC', max_length=5, verbose_name='Tipo de documento'),
        ),
    ]
